version: 0.1

phases:
  install:
    commands:
      - echo nothing
  pre_build:
    commands:
      - echo Logging in to Amazon ECR..
      - $(aws ecr get-login --region us-west-2)
  build:
    commands:
      - echo #### docker build ####
      - docker build -t flask .
      - docker tag flask:latest 282874131478.dkr.ecr.us-west-2.amazonaws.com/flask:latest
  post_build:
    commands:
      - echo #### docker push ####
      - docker push 282874131478.dkr.ecr.us-west-2.amazonaws.com/flask:latest
